
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: picamera2_server
    container_name: picamera2_server_container
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # X11 socket for display
      - shared-volume:/tmp
    privileged: true
    environment:
      - DISPLAY=$DISPLAY 
    command: python3 "server.py"
    
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: picamera2_client
    container_name: picamera2_client_container
    volumes:
      - shared-volume:/tmp
      - /run/udev:/run/udev:ro # for picamera
    privileged: true
    command: python3 "client.py"
    #depends_on:
    #  - server

volumes:
  shared-volume:
    driver: local
