version: '3.8'
services:
  ros:
    build:
      context: .
      dockerfile: Dockerfile.noetic
    image: noetic_rosserial_opencv
    container_name: noetic_rosserial_opencv_container
    volumes:
      - shared-volume:/var/run
      - ./output:/output  # Mount host directory to save video
    tty: true
    privileged: true
    environment:
      - ROS_DISTRO=noetic
    #command: /bin/bash -c "source /opt/ros/noetic/setup.bash && source /catkin_ws/devel/setup.bash && bash"
    
  picamera:
    build:
      context: .
      dockerfile: Dockerfile.picamera
    image: picamera2_opencv
    container_name: picamera2_opencv_container
    volumes:
      - shared-volume:/var/run
      - /run/udev:/run/udev:ro
      - ./output:/output
    privileged: true
    #command: /bin/bash -c "sleep 5 && python3 main.py"
    depends_on:
      - ros

volumes:
  shared-volume:
    driver: local
