FROM python:3.9-slim 

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-opencv \
    && apt-get -y clean && \
    apt-get -y purge && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /

COPY server.py ./server.py






